name: ui-build

on:
  push:
    paths:
      - 'ui-app/**'

jobs:

  build-x86:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cd ui-app && npm install && npm run build

      - name: package x86
        run: |
          tar -czf ui-app_x86_${{ github.sha }}.tar.gz ui-app/build

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload x86
        run: |
          aws s3 cp ui-app_x86_${{ github.sha }}.tar.gz \
          s3://${{ secrets.S3_BUCKET }}/ui-app/x86/


  build-arm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cd ui-app && npm install && npm run build

      - name: package arm
        run: |
          tar -czf ui-app_arm64_${{ github.sha }}.tar.gz ui-app/build

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload arm
        run: |
          aws s3 cp ui-app_arm64_${{ github.sha }}.tar.gz \
          s3://${{ secrets.S3_BUCKET }}/ui-app/arm64/
